### ISSUE TITLE
No .local/share/kabmat/data

### ISSUE THREAD

**Issue by ultraSsak** [PlankCipher/kabmat#3]
Hello, 
After installing with `sudo make install` app wont start
It seems it didn't create `~/.local/share/kabmat` directory, nor the "data" file
[install.log](https://github.com/PlankCipher/kabmat/files/8407403/install.log)
[execute.log](https://github.com/PlankCipher/kabmat/files/8407404/execute.log)

**Comment by PlankCipher** [comment]
I think it created them, but for the `root` user, because `sudo make install` isn't equivalent to `make install`. The first installs the app for the root user, the second installs it for the current user. And I assume you started it with `kabmat` and not `sudo kabmat`, so it couldn't find the file.

Try running these commands to install and run it with your user:
1. `sudo make clean` => to remove what `root` user built
2. `make install`
3. `kabmat`
